remote_theme: pmarsceill/just-the-docs

color_scheme: "dark"
theme: "just-the-docs"

title: Taterzens
description: >-
  Taterzens documentation.
#baseurl: "/Taterzens"
#url: "https://samolego.github.io"
github_username: samolego

gh_edit_link: true
gh_edit_link_text: "Want to improve the page? Fork it on GitHub."
gh_edit_repository: "https://github.com/samolego/Taterzens"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "edit"
